name: Deploy Production

on:
  push:
    branches: main

jobs:
  ci:
    uses: viniciussaturnino/pilar_case/.github/workflows/ci.yml@main
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Build app
        run: docker compose up -d app

  deploy:
    needs: [ci, build]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: true
